ALTER TABLE meta_data_column ADD COLUMN column_order INT UNIQUE;

INSERT INTO meta_data_column VALUES ('xenograft', null, null, 11);
INSERT INTO meta_data_column VALUES ('input material', null, null, 16);
INSERT INTO meta_data_column VALUES ('plate', 'single cell plate', null, 23);
INSERT INTO meta_data_column VALUES ('well position', 'single cell well position', null, 24);

UPDATE meta_data_column SET column_order = 22 WHERE column_name = 'antibody';
UPDATE meta_data_column SET column_order = 21 WHERE column_name = 'antibody target';
UPDATE meta_data_column SET column_order = 5 WHERE column_name = 'base count';
UPDATE meta_data_column SET column_order = 28 WHERE column_name = 'center';
UPDATE meta_data_column SET column_order = 36 WHERE column_name = 'comment';
UPDATE meta_data_column SET column_order = 6 WHERE column_name = 'cycle count';
UPDATE meta_data_column SET column_order = 2 WHERE column_name = 'fastq file name';
UPDATE meta_data_column SET column_order = 34 WHERE column_name = 'fastq generator';
UPDATE meta_data_column SET column_order = 27 WHERE column_name = 'ilse no';
UPDATE meta_data_column SET column_order = 26 WHERE column_name = 'index';
UPDATE meta_data_column SET column_order = 32 WHERE column_name = 'instrument model';
UPDATE meta_data_column SET column_order = 33 WHERE column_name = 'instrument platform';
UPDATE meta_data_column SET column_order = 31 WHERE column_name = 'lane no';
UPDATE meta_data_column SET column_order = 15 WHERE column_name = 'lib prep kit';
UPDATE meta_data_column SET column_order = 3 WHERE column_name = 'md5 sum';
UPDATE meta_data_column SET column_order = 13 WHERE column_name = 'phenotype';
UPDATE meta_data_column SET column_order = 9 WHERE column_name = 'patient id';
UPDATE meta_data_column SET column_order = 8 WHERE column_name = 'project';
UPDATE meta_data_column SET column_order = 7 WHERE column_name = 'read count';
UPDATE meta_data_column SET column_order = 4 WHERE column_name = 'read number';
UPDATE meta_data_column SET column_order = 30 WHERE column_name = 'run date';
UPDATE meta_data_column SET column_order = 29 WHERE column_name = 'run id';
UPDATE meta_data_column SET column_order = 1 WHERE column_name = 'sample name';
UPDATE meta_data_column SET column_order = 10 WHERE column_name = 'sample type';
UPDATE meta_data_column SET column_order = 35 WHERE column_name = 'sequencing kit';
UPDATE meta_data_column SET column_order = 14 WHERE column_name = 'sequencing read type';
UPDATE meta_data_column SET column_order = 18 WHERE column_name = 'sequencing type';
UPDATE meta_data_column SET column_order = 12 WHERE column_name = 'sex';
UPDATE meta_data_column SET column_order = 17 WHERE column_name = 'single cell';
UPDATE meta_data_column SET column_order = 25 WHERE column_name = 'species';
UPDATE meta_data_column SET column_order = 19 WHERE column_name = 'tagmentation';
UPDATE meta_data_column SET column_order = 20 WHERE column_name = 'tagmentation library';
